MODEL_NUDG=.FALSE.
MODEL_LHN=.TRUE.
MODEL_NH_NUDG=6
MODEL_NH_LHN=6
MODEL_BACK=6
MODEL_STOP=6
MODEL_BCANA=Y
#LOGSIM_PROCESS=rucn2_ope_ra_run
LETKF_WORKDIR=$WORKDIR/letkf
LETKF_DATADIR=$WORKDIR/letkf/data
LETKF_BIN=$WORK/srcgnu/3dvar/build/obj/var3d

