MODEL_BIN=$WORKDIR_BASE/srcintel/cosmo_5.08/radarbin_nud
PARENTMODEL=COSMO
PARENTMODEL_ARKI_DS=o_lm5_ope_forecast
PARENTMODEL_FREQINI=12
PARENTMODEL_FREQANA=1
PARENTMODEL_FREQFC=1
PARENTMODEL_QRQS=.TRUE.
MODEL_NUDG=.FALSE.
MODEL_LHN=.TRUE.
MODEL_NH_NUDG=4
MODEL_NH_LHN=4
MODEL_BACK=0
MODEL_STOP=18
MODEL_BCANA=N
#MODEL_SOIL_PARENT=Y
#MODEL_SNOW_PARENT=Y
MODEL_LAKE=Y
MODEL_SLOW_PAST_H=144
MODEL_FREQINI=3
case $TIME in
    00 | 12)
	MODEL_DELTABD=12
	;;
    03 | 15)
	MODEL_DELTABD=3
	;;
    06 | 18)
	MODEL_DELTABD=6
	;;
    09 | 21)
	MODEL_DELTABD=9
	;;
esac
ENS_TOTAL_MEMB=0
# setup for remote import
ARKI_SCAN_METHOD=configured_importer
#unset ARKI_IMPDIR
ARKI_SYNCDIR=$WORKDIR_BASE/import/sync_lami
ARKI_DLDIR=$WORKDIR_BASE/download
POSTPROC_LIST=(lami_make_arkiruc lami_make_vprof)
VPROF_NETWORK=cosmo_2I_vprof
MODEL_SIGNAL=cosmo_2I_fcruc
CONFIGURED_SIGNAL_METHOD=$IMPORT_SIGNAL_METHOD,meteohub
# setup for arkilocal
ARKI_DIR=$WORKDIR/arki
MODEL_ARCHIVE_ANA=$WORKDIR/../enda/archive

# suite timing
NWPWAITELAPS=10800
NWPWAITSOLAR=7200
NWPWAITSOLAR_RUN=2700
NWPWAITWAIT=30
