# definitions for parent model
PARENTMODEL=IFS
PARENTMODEL_ARKI_DS=$ARKI_URL/era5_ni
PARENTMODEL_FREQANA=3
PARENTMODEL_QRQS=.FALSE.
PARENTMODEL_STATIC=$HOME/data/ifs
IMPORT_SIGNAL_METHOD=
# configuration of assimilation
MODEL_BCANA=Y
MODEL_DELTABD=0
MODEL_SOIL_PARENT=N
MODEL_SNOW_PARENT=N
MODEL_LAKE=Y
MODEL_SLOW_PAST_H=144
MODEL_FREQINI=12
MODEL_BACK=$MODEL_FREQINI
MODEL_STOP=$MODEL_FREQINI
MODEL_LHN=.FALSE.
MODEL_NH_LHN=0
MODEL_NUDG=.FALSE.
MODEL_NH_NUDG=0
STOP_ON_FAIL=Y
