MODEL_NH_NUDG=$(($MODEL_FREQINI + 4))
MODEL_NH_LHN=$MODEL_FREQINI
MODEL_BACK=$MODEL_FREQINI
MODEL_STOP=$MODEL_FREQINI
MODEL_ARCHIVE_OUTPUT_ANA=$WORKDIR/archive
MODEL_SIGNAL=cosmo_5I_assim
NWPWAITELAPS=10800
NWPWAITSOLAR=36000
NWPWAITSOLAR_RUN=3600
NWPWAITWAIT=30

# setup for remote import
unset ARKI_IMPDIR
unset ARKI_SYNCDIR
#ARKI_SYNCDIR=$WORKDIR_BASE/import/sync_ftpmodelin
unset ARKI_DLDIR
#POSTPROC_LIST=(lami_make_arki5I)
#VPROF_NETWORK=cosmo_5I_assim_vprof
