BUFR_WORKDIR=$WORKDIR/bufr
case "$HOSTNAME" in
  *.metarpa | maial* ) # Arpae
	FTPDIR="BUFR/"
	OBSTYPES="AIRC AMDA AMDN B002 B004 OCEA PILO SHIP SYNN SYNO TEMP"
    ;;
  lami* ) # Cineca cloud
	FTPDIR=""
	OBSTYPES="AIRC AMDA AMDN B002 B004 OCEA PILO SHIP SYNN SYNO TEMP"
    ;;
esac
#obstypes="AIRC AMDA AMDN B002 B004 BUON OCEA PILN PILO RAOB SHIN SHIP SYNN SYNO TEMP"
